version: '3.8'

services:
  postgres:
    container_name: tga-friends-pg
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/pg:/data/postgres

  redis:
    container_name: tga-friends-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
